repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: detect-private-key
- repo: local
  hooks:
    - id: sort-gitignore
      name: Sort .gitignore (preserve comments)
      entry: >
        sh -c '
        tmp=$(mktemp) &&
        {
          grep "^#" .gitignore;
          grep -v "^#" .gitignore | grep -v "^$" | sort -u;
        } > "$tmp" &&
        mv "$tmp" .gitignore
        '
      language: system
      files: ^\.gitignore$
